### ISSUE TITLE
OOP ch8 질문

### ISSUE THREAD

**Issue by jseon-mi** [JeongSeonmi/OOP#2]
- call of reference 와 call of pointer의 차이

- swap 함수 앞에 Circle을 붙이고 안 붙히고의 차이. 클래스의 맴버변수 or 함수를 사용할때만 붙히면 되는가?

- 8-4 과제에서는 깊은 복사 생성자를 만들라고 했는데 얕은복사로 과제 제출했는데 점수 제대로 받음 왜그런걸까

- 과제 제출한 건 gpt가 "Book 클래스의 복사 생성자와 대입 연산자 오버로딩이 제공되지 않았기 때문에, 얕은 복사가 수행됩니다."라는데
 오버로딩이라는게 내가 만든 Book(const Book &book) 생성자같은거 말하는거인가

- 참조에 의한 호출 방식으로만 얕은 복사가 가능한가?

- 8-4는 참조의 의한 호출을 이용해서 만든 깊은 복사
 매개변수로 전달된 book 객체를 참조하여 새로운 객체를 생성 한다는데
 class BooK의 맴버변수.. 그니까 붕어빵 틀을 빌려온다는 느낌인가

- char* 방식이 아닌 string 방식
 C++에서 제공하는 string 라이브러리를 사용하면 알아서 따로 저장해주는가?

**Comment by songsuyoung** [comment]
1. call of reference 와 call of pointer의 차이
-> reference의 &와 pointer의 *의 차이를 생각하면 쉽다. 
reference의 특징이 무엇인가? 
- 실제 메모리를 잡지않는다. 
- 그 변수에 직접 연결되며, 별명이라고 칭하는 특징이 있다.
pointer의 특징이 무엇인가?
- 메모리에 포인터 변수 크기를 잡고 가리키는 영역을 저장한다는 것이 특징이다.

이 두개의 차이를 보면, call by reference는 직접 접근해서 변경을 의미하고, call by pointer는 직접 접근은 아니라는 것을 알 수 있다.(주소를 이용한 간접접근)

2. swap 함수 앞에 Circle을 붙이고 안 붙히고의 차이. 클래스의 맴버변수 or 함수를 사용할때만 붙히면 되는가?
-> 의미를 모름


8-4 과제에서는 깊은 복사 생성자를 만들라고 했는데 얕은복사로 과제 제출했는데 점수 제대로 받음 왜그런걸까
-> 깊은 복사와 얕은 복사의 차이를 알아야할듯 
대표적으로, 그 과제에 포인터가 없었는가? 를 생각하면 좋을듯
포인터가 있을 경우 깊은 복사를 통해서 붙여줘야함. 하지만 만약 멤버변수로 포인터가 없었더라면 얕은 복사로 컴파일러가 자동으로 수행시켜줄 수 있음

과제 제출한 건 gpt가 "Book 클래스의 복사 생성자와 대입 연산자 오버로딩이 제공되지 않았기 때문에, 얕은 복사가 수행됩니다."라는데
오버로딩이라는게 내가 만든 Book(const Book &book) 생성자같은거 말하는거인가
-> 놉. 저번에 나와 튜터링 진행했을 때, 컴파일러가 자동으로 복사생성자, 대입연산자를 만들어 낸다고 얘기했었음. 근데 너가 
직접 구현하지 않았으니까 컴파일에서 만들어낸 대입,복사 생성자에 의해 얕은 복사가 실시된것.

참조에 의한 호출 방식으로만 얕은 복사가 가능한가?
-> 의도를 모르겠으나 call by reference를 의미하는 것인가? 복사만 한다면 가능은 하겠지만, reference변수는 수정이 불가능함.
일반 변수에 파라미터로 받은 reference의 값을 받을 경우에는 가능.

8-4는 참조의 의한 호출을 이용해서 만든 깊은 복사
매개변수로 전달된 book 객체를 참조하여 새로운 객체를 생성 한다는데
class BooK의 맴버변수.. 그니까 붕어빵 틀을 빌려온다는 느낌인가

char* 방식이 아닌 string 방식
C++에서 제공하는 string 라이브러리를 사용하면 알아서 따로 저장해주는가?
-> char* 방식은 일단 C언어 방식임을 알아야함. char에서 string을 받으려고 하면 char에서 제공해주는 함수를 사용해야할것임.
-> string 의 경우 객체로 구현되어 있기 때문에 대입 연산자도 구현되어 있음. 그래서 string라이브러리를 사용하지 않고도 대입 복사 모두 가능함.
