### ISSUE TITLE
OOP ch9 질문

### ISSUE THREAD

**Issue by jseon-mi** [JeongSeonmi/OOP#3]
1.
 ![operator](https://github.com/JeongSeonmi/OOP/assets/92526287/20731ae5-3a84-4895-b99f-007e82c4243a)
return *this;는 현재 객체를 가리키는 포인터인 this를 역참조하여 객체 자체를 반환하는 구문이라는데 역참조라는 말이 머리에 뭔가 확 이해가 되지 않습니다.
현재 객체에 다시 연산한 값을 input해준다는 의미로 생각해도 괜찮나요?

 
2.
연산자 함수(operator) 앞의 리턴타입 부분이 Book(class 이름)일때와 리턴타입일때 차이는?
ex ) **Book** operator+=( );   랑    **bool** operator +=( );

![operator2](https://github.com/JeongSeonmi/OOP/assets/92526287/0ab78dbb-57b6-4769-97e7-6648c2052ceb)
클래스 선언부에서 리턴타입 부분에 **클래스이름을 넣을때**, 어떤 역할(기능)을 하는지 모르겠음
맴버함수에 클래스이름을 앞에 붙힐 이유가 있나요?

3.
https://sobamemil.tistory.com/90
이 글은 클래스이름& operator+=( );  형태로 사용했는데 &를 붙히는 이유가 뭔가요

4.
*지난번 8에서 기억안난다고 했던 질문*
![fghjjghj](https://github.com/JeongSeonmi/OOP/assets/92526287/e0f11a5d-6694-4c37-aeb6-d1e5eeb8f716)
여기서 Circle getCircle() <- 이 함수는 클래스 선언부에 선언되지 않아서 전역함수인거같은데 Circle이 붙는 이유를 모르겠습니다.

**Comment by songsuyoung** [comment]
OPP ch 9 질문 답변

1. c++에서 this의 개념을 생각해보자.
this는 객체 자신 주소를 의미(참조)한다. 역참조란 쉽게 말하면, 해당 값이 저장하고 있는 주소로 이동하여 결과값을 확인해 출력한다를 의미한다.
즉, 연산자 재정의+함수에서 가격을 더한 결과를 가진 객체, 그 자체를 반환한다를 의미한다.

2. 연산자 재정의 의미를 생각해보자
Book이라는 사용자 정의 클래스에 대해서 실제로는 +연산을 제공하지 않는다. 근데, 위 함수(1번)처럼 +연산을 이용해서 가격을 더한 값을 반환하고 싶을때, 실제로는 오류가 나지만, 연산자 재정의를 이용해 +에 대한 함수를 작성하게 되면 함수로 따로 작성할 필요없이 + 키워드 만으로도 덧셈을 적용할 수 있음.

- 리턴 타입에 클래스 이름을 넣는 이유는 
Book p(“…”,1000);
Book k(“…”,500);

p+=10;// p의 price가 1500으로 변한채 함수 호출 없이도 덧셈이 진행될것임.

3. 2번과 마찬가지
그냥 Book을 호출할 경우 지역변수처럼 생성 후 블록이 끝나면 메모리를 해제하는 형태인데, reference를 이용하게 되면 그 자체를 이용하기 때문에 쓸데없는 메모리 소비가 없다는 장점이 있음.

4. 아무 의미 없는듯
그냥 지역 블록내에서 하나의 객체를 생성하고 반환 기능을 하는 함수이다.
그리고, 클래스 내에 선언되지 않더라도 4번처럼 사용가능하다.
Class내에 선언된 메소드의 경우 객체가 가져야할 꼭 필요요소이지만, getCircle의 기능을 보았을 때, Circle 클래스내에 선언되어야 하는가? 를 생각해보면 좋을듯!
